name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main   # trigger when code pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd yogesh/git_practice
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            pkill -f uvicorn
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
