name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          debug: true  
          script: |
            cd fastapi/git_practice
            git pull origin main
            source ../venv/bin/activate
            pip install -r requirements.txt
            pkill -f "uvicorn main:app" || true
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &